development:
  adapter: postgresql
  database: news_tracker_development

test:
  adapter: postgresql
  database: news_tracker_test

production:
  adapter: postgresql
  database: news_tracker_production
