# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df3e856e88b16186d9bcb12fca902b1f52209378cd8bed2e04032e7e8b3d93d55fba59b309b1e50d50a84b6647edf78324cb97d14c2c11b4c859bea6e428455

test:
  secret_key_base: 8b94ea1cfc4bd12528e02285cd872921a2edb4f8c917992b3af0d0a15a9b94d33c2655b5cd79d0f678b63f1f842de00f2506be75667e9e187a354e33fde13a28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
